services:
  - type: web
    name: placement-tracker
    runtime: static
    buildCommand: npm run build
    publishDir: dist
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 